export const productsData = [
  {
    id: 1,
    name: 'Café preto',
    quantity: 9,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café'],
    price: 5,
  },
  {
    id: 2,
    name: 'Café Marrom',
    quantity: 0,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 3,
    name: 'Café Ciano',
    quantity: 4,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 4,
    name: 'Café Lilas',
    quantity: 25,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 5,
    name: 'Café Roxo',
    quantity: 10,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 6,
    name: 'Café Turquesa',
    quantity: 0,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 7,
    name: 'Café Bege',
    quantity: 5,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 8,
    name: 'Café Vantablack',
    quantity: 0,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 9,
    name: 'Café Amarelo',
    quantity: 0,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
  {
    id: 10,
    name: 'Café Magenta',
    quantity: 0,
    description: 'teste',
    image: 'https://upload.wikimedia.org/wikipedia/commons/4/45/A_small_cup_of_coffee.JPG',
    categories: ['bebida', 'café', 'Misteriosa'],
    price: 5,
  },
];
